config/routes.rb
Rails.application.routes.draw do
  resources :sesiones #agrega ruta de sesiones
  resources :evaluaciones
  resources :turnos
  resources :logins
  resources :usuarios
  resources :agencias

  root 'logins#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
  	belongs_to :usuario
  	
	validates :estado, presence:true
	validates :sesion, presence:true
	validates :clase_usuario, presence:true

	

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:estado, :sesion, :clase_usuario, :usuario_id)
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :estado %><br>
      <%= f.number_field :estado, class: 'form-control'  %>
    </div>
  </div>  
  <div class="col-md-4 col-sm-6 col-xs-12">  
    <div class="form-group">
      <%= f.label :sesion %><br>
      <%= f.text_field :sesion, class: 'form-control'  %>
    </div>
  </div>  
  <div class="col-md-4 col-sm-6 col-xs-12">  
    <div class="form-group">
      <%= f.label :clase_usuario %><br>
      <%= f.number_field :clase_usuario, class: 'form-control'  %>
    </div>
  </div>  
    <div class="form-group">
     <%= f.submit 'Guardar', class: 'btn btn-primary' %> 
    </div>
</div>

<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @login %> |
<%= link_to 'Atrás', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Logins</h4>

<table class="table table-striped table-condensed table-hover "> 
  <thead>
    <tr>
      <th>Estado</th>
      <th>Sesion</th>
      <th>Clase usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.estado %></td>
        <td><%= login.sesion %></td>
        <td><%= login.clase_usuario %></td>
        <td><%= link_to 'Mostrar', login %></td>
        <td><%= link_to 'Editar', edit_login_path(login) %></td>
        <td><%= link_to 'Eliminar', login, method: :delete, data: { confirm: 'Está seguro de eliminar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Login', new_login_path, class:'btn' %>

app/views/logins/new.html.erb
<h1>Nuevo Login</h1>

<%= render 'form' %>

<%= link_to 'Atrás', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @login.estado %>
</p>

<p>
  <strong>Sesion:</strong>
  <%= @login.sesion %>
</p>

<p>
  <strong>Clase usuario:</strong>
  <%= @login.clase_usuario %>
</p>


<%= link_to 'Editar', edit_login_path(@login) %> |
<%= link_to 'Atrás', logins_path %>