config/routes.rb
Rails.application.routes.draw do
  resources :sesiones #agrega ruta de sesiones
  resources :evaluaciones
  resources :turnos
  resources :logins
  resources :usuarios
  resources :agencias

  root 'logins#index'

end

app/models/agencia.rb
class Agencia < ActiveRecord::Base
	has_many :usuarios
	has_many :turnos

	validates :nombre, presence: true
	validates :direccion, presence: true
end

app/controllers/agencias_controller.rb
class AgenciasController < ApplicationController
  before_action :authenticate
  before_action :set_agencia, only: [:show, :edit, :update, :destroy]

  # GET /agencias
  # GET /agencias.json
  def index
    @agencias = Agencia.all
  end

  # GET /agencias/1
  # GET /agencias/1.json
  def show
  end

  # GET /agencias/new
  def new
    @agencia = Agencia.new
  end

  # GET /agencias/1/edit
  def edit
  end

  # POST /agencias
  # POST /agencias.json
  def create
    @agencia = Agencia.new(agencia_params)

    respond_to do |format|
      if @agencia.save
        format.html { redirect_to @agencia, notice: 'Agencia was successfully created.' }
        format.json { render :show, status: :created, location: @agencia }
      else
        format.html { render :new }
        format.json { render json: @agencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencias/1
  # PATCH/PUT /agencias/1.json
  def update
    respond_to do |format|
      if @agencia.update(agencia_params)
        format.html { redirect_to @agencia, notice: 'Agencia was successfully updated.' }
        format.json { render :show, status: :ok, location: @agencia }
      else
        format.html { render :edit }
        format.json { render json: @agencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencias/1
  # DELETE /agencias/1.json
  def destroy
    @agencia.destroy
    respond_to do |format|
      format.html { redirect_to agencias_url, notice: 'Agencia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agencia
      @agencia = Agencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agencia_params
      params.require(:agencia).permit(:nombre, :direccion)
    end
end

app/helpers/agencias_helper.rb
module AgenciasHelper
end

app/views/agencias/_form.html.erb
<%= form_for(@agencia) do |f| %>
  <% if @agencia.errors.any? %>
    <div id="error_explanation">
       <h2><%= t('errors.template.header', model: 'Agencia', count: @agenciia.errors.count)%></h2>
       <!--  <h2><%= pluralize(@agencia.errors.count, "error") %> prohibited this agencia from being saved:</h2> -->

       <!--la linea anterior sirve para manejar los errores en español y los valida usando archivo ubicado dentro de la gema rails-i18n -->

      <ul>
      <% @agencia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">  
  <div class="col-md-4 col-sm-6 col-xs-12"> <!-- el 4 indica que tenga 3 columnas en el formulario    
     cuando se visualiza en el explorador por que boostrap maneja 12 columnas 3*4=12-->
    <div class="form-group">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
        <%= f.label :direccion %><br>
        <%= f.text_field :direccion, class: 'form-control' %>
    </div>
  </div>   
</div>

<br />
<!-- <div class="actions"> -->
<div class="form-group">
   <%= f.submit 'Guardar', class: 'btn btn-primary' %>  
<!--    <%= f.submit %> -->
 </div>
<% end %>

app/views/agencias/edit.html.erb
<h1>Editar Agencia</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @agencia %> |
<%= link_to 'Atrás', agencias_path %>

app/views/agencias/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Agencias</h4>

<table class="table table-striped table-condensed table-hover "> 
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencias.each do |agencia| %>
      <tr>
        <td><%= agencia.nombre %></td>
        <td><%= agencia.direccion %></td>
        <td><%= link_to 'Mostrar', agencia %></td>
        <td><%= link_to 'Editar', edit_agencia_path(agencia) %></td>
        <td><%= link_to 'Eliminar', agencia, method: :delete, data: { confirm: 'Está seguro de eliminar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicione Agencia', new_agencia_path, class:'btn btn-primary' %>

app/views/agencias/new.html.erb
<h1>Nueva Agencia</h1>

<%= render 'form' %>

<%= link_to 'Atrás', agencias_path %>

app/views/agencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @agencia.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @agencia.direccion %>
</p>

<%= link_to 'Editar', edit_agencia_path(@agencia) %> |
<%= link_to 'Atrás', agencias_path %>