config/routes.rb
Rails.application.routes.draw do
  resources :sesiones #agrega ruta de sesiones
  resources :evaluaciones
  resources :turnos
  resources :logins
  resources :usuarios
  resources :agencias

  root 'logins#index'

end

app/models/turno.rb
require 'csv'
class Turno < ActiveRecord::Base
  	include Export

  	has_many :evaluaciones
  
  	belongs_to :usuario
  	belongs_to :agencia
	
	validates :nombre, presence:true
	validates :resumen, presence:true
	validates :descripcion, presence:true
	validates :hora_ingreso, presence:true
	validates :hora_atencion, presence:true
	validates :hora_finalizacion, presence:true
	validates :comentario_atencion, presence:true
	validates :estado, presence:true
	
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :authenticate
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all

    respond_to do |format|
      format.html
      format.csv { send_data Turno.to_csv }
      format.json
    end
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turno_params
      params.require(:turno).permit(:nombre, :resumen, :descripcion, :hora_ingreso, :hora_atencion, :hora_finalizacion, :usuario_id, :comentario_atencion, :estado, :agencia_id)
    end
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/turnos/_form.html.erb
<%= form_for(@turno) do |f| %>
  <% if @turno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turno.errors.count, "error") %> prohibited this turno from being saved:</h2>

      <ul>
      <% @turno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :resumen %><br>
        <%= f.text_field :resumen, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :descripcion %><br>
        <%= f.text_area :descripcion, class: 'form-control' %>
      </div>
    </div>   
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :hora_ingreso %><br>
        <%= f.datetime_select :hora_ingreso, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :hora_atencion %><br>
        <%= f.datetime_select :hora_atencion, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :hora_finalizacion %><br>
        <%= f.datetime_select :hora_finalizacion, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :usuario_id %><br>
        <%= f.collection_select :usuario_id, Usuario.all, :id, :login, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :comentario_atencion %><br>
        <%= f.text_area :comentario_atencion, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :estado %><br>
        <%= f.number_field :estado, class: 'form-control' %>
      </div>
    </div>  
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :agencia_id %><br>
        <%= f.collection_select :agencia_id, Agencia.all, :id, :nombre, class: 'form-control' %>
      </div>
    </div>  
 </div>
 <br />   
    <div class="form-group">
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    </div>  
<% end %>

app/views/turnos/edit.html.erb
<h1>Editing Turno</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @turno %> |
<%= link_to 'Atrás', turnos_path %>

app/views/turnos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Turnos</h4>

<table class="table table-striped table-condensed table-hover "> 
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Resumen</th>
      <th>Descripcion</th>
      <th>Hora ingreso</th>
      <th>Hora atencion</th>
      <th>Hora finalizacion</th>
      <th>Usuario</th>
      <th>Comentario atencion</th>
      <th>Estado</th>
      <th>Agencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.nombre %></td>
        <td><%= turno.resumen %></td>
        <td><%= turno.descripcion %></td>
        <td><%= turno.hora_ingreso %></td>
        <td><%= turno.hora_atencion %></td>
        <td><%= turno.hora_finalizacion %></td>
        <td><%= turno.usuario.login %></td>
        <td><%= turno.comentario_atencion %></td>
        <td><%= turno.estado %></td>
        <td><%= turno.agencia.nombre %></td>
        <td><%= link_to 'Mostrar', turno %></td>
        <td><%= link_to 'Editar', edit_turno_path(turno) %></td>
        <td><%= link_to 'Eliminar', turno, method: :delete, data: { confirm: 'Está seguro de eliminar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Turno', new_turno_path, class:'btn' %>
<%= link_to 'Descargar csv', turnos_path(format: :csv), class: 'btn btn-primary'%>

app/views/turnos/new.html.erb
<h1>Nuevo Turno</h1>

<%= render 'form' %>

<%= link_to 'Atrás', turnos_path %>

app/views/turnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @turno.nombre %>
</p>

<p>
  <strong>Resumen:</strong>
  <%= @turno.resumen %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @turno.descripcion %>
</p>

<p>
  <strong>Hora ingreso:</strong>
  <%= @turno.hora_ingreso %>
</p>

<p>
  <strong>Hora atencion:</strong>
  <%= @turno.hora_atencion %>
</p>

<p>
  <strong>Hora finalizacion:</strong>
  <%= @turno.hora_finalizacion %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @turno.usuario.login %>
</p>

<p>
  <strong>Comentario atencion:</strong>
  <%= @turno.comentario_atencion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @turno.estado %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @turno.agencia.nombre %>
</p>

<%= link_to 'Editar', edit_turno_path(@turno) %> |
<%= link_to 'Atrás', turnos_path %>